title: Constance's Awesome Blog
author: ConstanceMK
email: constance.kern@lexisnexisrisk.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Constance Awesome Blog, where we talk about awesome things like singing and personal growth!

# social links
twitter_username: Cinnabars # DO NOT include the @ character, or else the build will fail!
github_username:  ConstanceMK # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
